# .github/workflows/generate-snake.yml

name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation (Cyberpunk Mode)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: raphaelgdn
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#8A2BE2"          # Roxo neon (Cyberpunk)
          background_color: "#000000"     # Preto total

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
