# .github/workflows/generate-snake.yml

name: Generate Snake Animation

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente pelo botão do GitHub

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Gerar o SVG da Snake
      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: raphaelgdn
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Step 3: Publicar no branch output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
